name: Electric Penguin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6205801938194782
title: The Electric Penguin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#860000'
    - '#ffffff'
    - '#959595'
    - '#5f5f5f'
  brandStrength: 0.6875
  lightness: 0.9920127815566957
  saturation: 0.13077022600919008
  rhythmicContrast: 0.7970138685777783
purpose: []
