typography_spectrum: 0.35418
color:
  brandColors:
    - '#020202'
    - '#860000'
    - '#ffffff'
    - '#959595'
    - '#5f5f5f'
  brandStrength: 0.6875
  lightness: 0.9920127815566957
  saturation: 0.13077022600919008
  rhythmicContrast: 0.7970138685777783
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Electric Penguin
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Electric Penguin
description: A lovely tagline goes here...
purpose: []
